// Types
export type { UserDTO, AuthResponse, RefreshResponse } from "./types/auth"
export type { HabitType, SubHabitDTO, HabitLogDTO, HabitStatsDTO, HabitRequest, LogRequest } from "./types/habit"
export type {
  HabitResponse, SubHabitResponse, TodayHabitEntry, HabitLogEntry,
  WeeklyStatEntry, StatsSummary, UserProfile,
} from "./types/api"

// Lib
export { cn } from "./lib/utils"
export { getRandomColor } from "./lib/colors"
export { gsap, useGSAP, ScrollTrigger, SplitText } from "./lib/gsap"
export { pageVariants, staggerContainer, itemVariants } from "./lib/animations"

// Hooks
export { useIsMobile } from "./hooks/use-mobile.tsx"
export { usePreferences } from "./hooks/use-preferences"
export { useToast } from "./hooks/use-toast"

// Store
export { useAuthStore } from "./store/authStore"
export { useHabitStore } from "./store/habitStore"
export { useOfflineStore } from "./store/offlineStore"

// Components - UI
export { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "./components/ui/accordion"
export { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogOverlay, AlertDialogPortal, AlertDialogTitle, AlertDialogTrigger } from "./components/ui/alert-dialog"
export { Alert, AlertDescription, AlertTitle } from "./components/ui/alert"
export { Avatar, AvatarFallback, AvatarImage } from "./components/ui/avatar"
export { Badge, badgeVariants } from "./components/ui/badge"
export { Breadcrumb, BreadcrumbEllipsis, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "./components/ui/breadcrumb"
export { Button, buttonVariants } from "./components/ui/button"
export { ButtonGroup, ButtonGroupSeparator, ButtonGroupText } from "./components/ui/button-group"
export { Calendar } from "./components/ui/calendar"
export { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "./components/ui/card"
export { Carousel, type CarouselApi, CarouselContent, CarouselItem, CarouselPrevious, CarouselNext } from "./components/ui/carousel"
export { ChartContainer, ChartLegend, ChartLegendContent, ChartStyle, ChartTooltip, ChartTooltipContent } from "./components/ui/chart"
export { Checkbox } from "./components/ui/checkbox"
export { Command, CommandDialog, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList, CommandSeparator, CommandShortcut } from "./components/ui/command"
export { ContextMenu, ContextMenuCheckboxItem, ContextMenuContent, ContextMenuGroup, ContextMenuItem, ContextMenuLabel, ContextMenuPortal, ContextMenuRadioGroup, ContextMenuRadioItem, ContextMenuSeparator, ContextMenuShortcut, ContextMenuSub, ContextMenuSubContent, ContextMenuSubTrigger, ContextMenuTrigger } from "./components/ui/context-menu"
export { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogOverlay, DialogPortal, DialogTitle, DialogTrigger } from "./components/ui/dialog"
export { Drawer, DrawerClose, DrawerContent, DrawerDescription, DrawerFooter, DrawerHeader, DrawerOverlay, DrawerPortal, DrawerTitle, DrawerTrigger } from "./components/ui/drawer"
export { DropdownMenu, DropdownMenuCheckboxItem, DropdownMenuContent, DropdownMenuGroup, DropdownMenuItem, DropdownMenuLabel, DropdownMenuPortal, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuShortcut, DropdownMenuSub, DropdownMenuSubContent, DropdownMenuSubTrigger, DropdownMenuTrigger } from "./components/ui/dropdown-menu"
export { Empty } from "./components/ui/empty"
export { Field, FieldLabel, FieldDescription, FieldError, FieldContent, FieldTitle } from "./components/ui/field"
export { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from "./components/ui/form"
export { HoverCard, HoverCardContent, HoverCardTrigger } from "./components/ui/hover-card"
export { Input } from "./components/ui/input"
export { InputGroup } from "./components/ui/input-group"
export { InputOTP, InputOTPGroup, InputOTPSeparator, InputOTPSlot } from "./components/ui/input-otp"
export { Item, ItemMedia, ItemContent, ItemActions, ItemGroup, ItemSeparator, ItemTitle } from "./components/ui/item"
export { Kbd } from "./components/ui/kbd"
export { Label } from "./components/ui/label"
export { Menubar, MenubarCheckboxItem, MenubarContent, MenubarGroup, MenubarItem, MenubarLabel, MenubarMenu, MenubarPortal, MenubarRadioGroup, MenubarRadioItem, MenubarSeparator, MenubarShortcut, MenubarSub, MenubarSubContent, MenubarSubTrigger, MenubarTrigger } from "./components/ui/menubar"
export { NavigationMenu, NavigationMenuContent, NavigationMenuIndicator, NavigationMenuItem, NavigationMenuLink, NavigationMenuList, NavigationMenuTrigger, navigationMenuTriggerStyle } from "./components/ui/navigation-menu"
export { Pagination, PaginationContent, PaginationEllipsis, PaginationItem, PaginationLink, PaginationNext, PaginationPrevious } from "./components/ui/pagination"
export { Popover, PopoverAnchor, PopoverContent, PopoverTrigger } from "./components/ui/popover"
export { Progress } from "./components/ui/progress"
export { RadioGroup, RadioGroupItem } from "./components/ui/radio-group"
export { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "./components/ui/resizable"
export { ScrollArea, ScrollBar } from "./components/ui/scroll-area"
export { Select, SelectContent, SelectGroup, SelectItem, SelectLabel, SelectScrollDownButton, SelectScrollUpButton, SelectSeparator, SelectTrigger, SelectValue } from "./components/ui/select"
export { Separator } from "./components/ui/separator"
export { Sheet, SheetClose, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetOverlay, SheetPortal, SheetTitle, SheetTrigger } from "./components/ui/sheet"
export { Sidebar, SidebarContent, SidebarGroup, SidebarGroupAction, SidebarGroupContent, SidebarGroupLabel, SidebarHeader, SidebarInput, SidebarInset, SidebarMenu, SidebarMenuAction, SidebarMenuBadge, SidebarMenuButton, SidebarMenuItem, SidebarMenuSkeleton, SidebarMenuSub, SidebarMenuSubButton, SidebarMenuSubItem, SidebarProvider, SidebarRail, SidebarSeparator, SidebarTrigger, useSidebar } from "./components/ui/sidebar"
export { Skeleton } from "./components/ui/skeleton"
export { Slider } from "./components/ui/slider"
export { Spinner } from "./components/ui/spinner"
export { Switch } from "./components/ui/switch"
export { Table, TableBody, TableCaption, TableCell, TableFooter, TableHead, TableHeader, TableRow } from "./components/ui/table"
export { Tabs, TabsContent, TabsList, TabsTrigger } from "./components/ui/tabs"
export { Textarea } from "./components/ui/textarea"
export { Toast, ToastAction, ToastClose, ToastDescription, ToastProvider, ToastTitle, ToastViewport } from "./components/ui/toast"
export { Toaster } from "./components/ui/toaster"
export { Toggle } from "./components/ui/toggle"
export { ToggleGroup, ToggleGroupItem } from "./components/ui/toggle-group"
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "./components/ui/tooltip"

// Components - Shared
export { default as AnimatedList } from "./components/shared/AnimatedList"
export { HabitSummaryCardFront, HabitSummaryCardBack } from "./components/shared/HabitSummaryCard"
export { IsleLogo } from "./components/shared/IsleLogo"
export { IsleLogoFont } from "./components/shared/IsleLogoFont"
export { default as PageReveal } from "./components/shared/PageReveal"
export { default as Reveal } from "./components/shared/Reveal"
export { default as RevealText } from "./components/shared/RevealText"
export { default as TiltedCard } from "./components/shared/TiltedCard"
export { ThemeToggle } from "./components/shared/theme-toggle"

// Components - Habits
export { HabitFormDrawer } from "./components/habits/HabitFormDrawer"
export { HabitHistoryGrid } from "./components/habits/HabitHistoryGrid"
export { RecurrencePicker } from "./components/habits/RecurrencePicker"
export { StreakRing } from "./components/habits/StreakRing"
export { WeeklyChart } from "./components/habits/WeeklyChart"

// Components - Theme
export { ThemeProvider, useTheme } from "./components/theme-provider"
